from django.contrib import admin
from billing.models import *
class InvoicesAdmin(admin.ModelAdmin):
    exclude = ('invno',)
admin.site.register(Account_types)
admin.site.register(Articles)
admin.site.register(ArticlesB)
admin.site.register(Banks)
admin.site.register(Bills)
admin.site.register(Components)
admin.site.register(ComponentsB)
admin.site.register(Contract)
admin.site.register(Contract_types)
admin.site.register(Contractor_types)
admin.site.register(Contractors)
admin.site.register(Current_accounts)
admin.site.register(Demand_details)
admin.site.register(Demands)
admin.site.register(Devices)
admin.site.register(Employees)
admin.site.register(Factures)
admin.site.register(Imprest_reports)
admin.site.register(In_waybill_details)
admin.site.register(In_waybills)
admin.site.register(Invoice_types)
admin.site.register(Invoices, InvoicesAdmin)
admin.site.register(Lunch_details)
admin.site.register(Materials)
admin.site.register(Materials_lib)
admin.site.register(Out_waybill_details)
admin.site.register(Out_waybills)
admin.site.register(Parts)
admin.site.register(Parts_lib)
admin.site.register(Parts_spec)
admin.site.register(Pay_details)
admin.site.register(Payed_factures)
admin.site.register(Payed_inwaybills)
admin.site.register(Payed_waybills)
admin.site.register(Payment_orders)
admin.site.register(Payment_orders_method)
admin.site.register(Payment_orders_type)
admin.site.register(Payments)
admin.site.register(Perf_details)
admin.site.register(Prod_lunch)
admin.site.register(Prod_perf)
admin.site.register(Prod_ship)
admin.site.register(Prod_types1)
admin.site.register(Prod_types2)
admin.site.register(Prod_types3)
admin.site.register(Products)
admin.site.register(Ship_details)
admin.site.register(Stores)
admin.site.register(Sub_articles)
admin.site.register(Sub_invoices)
admin.site.register(Units)
admin.site.register(Waybill_types)

